backend:
  name: github
  repo: gangsthub/isaac
  accept_roles: #optional - accepts all users if left out
    - admin

media_folder: "static/uploads"
public_folder: '/images/uploads' # The src attribute for uploaded media will begin with /images/uploads

collections: # A list of collections the CMS should be able to edit
  - name: "Canvas" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Canvas" # Used in the UI, ie.: "New Post"
    folder: "content/canvas"
    slug: "{{year}}-{{slug}}"
    create: true # Allow users to create new documents in this collection
    format: 'json'
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mma"}
      - {label: "Cover Image", name: "image", widget: "image", required: true, tagname: ""}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "SEO Description", name: "description", widget: "text", required: true, pattern: ["^.{50,300}$", "Must be within 50 and 300 chars"]}
