backend:
  name: github
  repo: gangsthub/isaac

media_folder: "static/uploads"

collections: # A list of collections the CMS should be able to edit
  - name: "Canvas" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Canvas" # Used in the UI, ie.: "New Post"
    folder: "content/canvas"
    slug: "{{year}}-{{slug}}"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mma"}
      - {label: "Cover Image", name: "image", widget: "image", required: false, tagname: ""}
      - {label: "Body", name: "body", widget: "markdown"}
    meta:
      - {label: "SEO Description", name: "description", widget: "text"}
